### ISSUE TITLE
Language Detector should use simple_tokenizer

### ISSUE THREAD

**Issue by juanjoDiaz** [adbar/simplemma#36]
Hi @adbar ,

As I was refactoring the library, I noticed that `LanguageDetector` does NOT use the simple_tokenizer.
Instead, it uses a regex (`SPLIT_INPUT = re.compile(r"[^\W\d_]{3,}")`).

For example, that regex return empty for `" aa "` whereas the tokenizer returns `["aa"]` as you would expect.

I think that it should use the tokenizer so results are consistent and then filter out punctuation symbols.

Also, if you accept my proposal to move the library to classes, the user could provide it's own tokenizer to the language detector if he would like too.

P.S.: I would rather to review my big refactor before applying any other changes to avoid a constant conflict in the PR 🙂

**Comment by adbar** [comment]
I thought this would spare some time and improve detection accuracy, because smaller units like "aa" are left apart. The longer a word, the stronger the signal in this context.

Filtering out punctuation symbols wouldn't be enough, there are digits/numbers etc. So in the end it would mean a complete refactoring with potentially little benefit.

I believe it's fair that language detection uses its own tokenization but I'm also open to letting the users provide their own input or tokenization function. Let's keep it as a open question for now, we can see the rest later.
