### ISSUE TITLE
Custom token sampling in prepare_text() for language identification

### ISSUE THREAD

**Issue by adbar** [adbar/simplemma#45]
What if we want to offer the users a possibility to customize the sampling logic?
How could we do this without globally overriding this method?

_Originally posted by @juanjoDiaz in https://github.com/adbar/simplemma/pull/42#discussion_r1085860860_

**Comment by adbar** [comment]
A first step is this direction but it's not everything, the question remains open.

**Comment by juanjoDiaz** [comment]
Hi @adbar ,

It's a step indeed. But not very complete 😅

It's not only about the regex. It's a matter of how you split, how you choose the words to sample, how big the sample is, etc.

Also, it doesn't solve the problem that I've been highlighting since the beginning. The `prepare_text` calls are still hardcoded in the other functions of the language detector file so it can't be configure without rewriting those functions...

**Comment by adbar** [comment]
You're right, feel free to write a PR tackling this problem.

Please just make sure the current behavior stays untouched (i.e. users don't need to do any adjustments), we can always add the customization to the docs.
