### ISSUE TITLE
Separate scripts used to create the dictionaries from actual src & tests

### ISSUE THREAD

**Issue by juanjoDiaz** [adbar/simplemma#49]
`tests/udscore.py` and `src/dictionary_pickler.py` seem to be scripts used to create the dictionaries and validate their quality.

I suggest that they are moved to a separate folder `training` or whatever you want

**Comment by adbar** [comment]
Thanks for the suggestion. Indeed they could be left out of the library distributed on Pypi because they don't bring anything for the regular user. They even require particular dependencies (like `udscore.py`) which could be specified in a separate requirements file.

As for the structure it would probably make sense to create `eval/` and `training/` directories.

**Comment by adbar** [comment]
Now there is an `eval/` directory, I'm not sure about `training/`, excluding `dictionary_pickler.py` in the `MANIFEST.in` file would be enough. That way this file wouldn't be released with the package.
